### ISSUE TITLE
Run tests on travis?

### ISSUE THREAD

**Issue by bali182** [sdgluck/mewt#5]
I just created a PR and noticed that the tests are not running (good thing I checked locally). Would you consider integrating the repo with [TravisCI](https://travis-ci.org/)? After adding the repo there, the only you have to do is add a `.travis.yml` file in the root:

```yaml
language: node_js
node_js:
  - "6.1"
  - "6.0" # Also add whatever version you want to test with
script:
  - npm test
notifications:
  email: false # This is optional, I always turn it off since I check it anyways fairly often
```
